// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.1
//   protoc               v6.33.0
// source: trip.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "trip";

export interface CreateTripRequest {
  userId: string;
}

export interface AcceptTripRequest {
  id: string;
  driverId: string;
}

export interface TripId {
  id: string;
}

export interface TripResponse {
  id: string;
  userId: string;
  driverId?: string | undefined;
  status: string;
}

export const TRIP_PACKAGE_NAME = "trip";

export interface TripServiceClient {
  createTrip(request: CreateTripRequest): Observable<TripResponse>;

  getTripById(request: TripId): Observable<TripResponse>;

  cancelTrip(request: TripId): Observable<TripResponse>;

  acceptTrip(request: AcceptTripRequest): Observable<TripResponse>;

  startTrip(request: TripId): Observable<TripResponse>;

  completeTrip(request: TripId): Observable<TripResponse>;
}

export interface TripServiceController {
  createTrip(request: CreateTripRequest): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  getTripById(request: TripId): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  cancelTrip(request: TripId): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  acceptTrip(request: AcceptTripRequest): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  startTrip(request: TripId): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  completeTrip(request: TripId): Promise<TripResponse> | Observable<TripResponse> | TripResponse;
}

export function TripServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTrip",
      "getTripById",
      "cancelTrip",
      "acceptTrip",
      "startTrip",
      "completeTrip",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TripService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TripService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRIP_SERVICE_NAME = "TripService";
