// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.1
//   protoc               v6.33.0
// source: trip.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import {
  CreateTripRequest,
  AcceptTripRequest,
  TripId,
  GetTripsRequest,
  UpdateTripRequest,
} from '../dto/request';
import { TripResponse, TripsListResponse } from '../dto/response';

export const protobufPackage = 'trip';

export const TRIP_PACKAGE_NAME = 'trip';

export interface TripServiceClient {
  createTrip(request: CreateTripRequest): Observable<TripResponse>;

  getTripById(request: TripId): Observable<TripResponse>;

  getTrips(request: GetTripsRequest): Observable<TripsListResponse>;

  updateTrip(request: UpdateTripRequest): Observable<TripResponse>;

  cancelTrip(request: TripId): Observable<TripResponse>;

  acceptTrip(request: AcceptTripRequest): Observable<TripResponse>;

  startTrip(request: TripId): Observable<TripResponse>;

  completeTrip(request: TripId): Observable<TripResponse>;
}

export interface TripServiceController {
  createTrip(
    request: CreateTripRequest
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  getTripById(
    request: TripId
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  getTrips(
    request: GetTripsRequest
  ):
    | Promise<TripsListResponse>
    | Observable<TripsListResponse>
    | TripsListResponse;

  updateTrip(
    request: UpdateTripRequest
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  cancelTrip(
    request: TripId
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  acceptTrip(
    request: AcceptTripRequest
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  startTrip(
    request: TripId
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  completeTrip(
    request: TripId
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;
}

export function TripServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createTrip',
      'getTripById',
      'getTrips',
      'updateTrip',
      'cancelTrip',
      'acceptTrip',
      'startTrip',
      'completeTrip',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcMethod('TripService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcStreamMethod('TripService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
  };
}

export const TRIP_SERVICE_NAME = 'TripService';
